CREATE TABLE `tx_trade` (
  `tx_trade_no` varchar(32) NOT NULL COMMENT '交易流水号',
  `org_tx_trade_no` varchar(32) NOT NULL DEFAULT '' COMMENT '原交易流水号',
  `merchant_id` varchar(16) NOT NULL COMMENT '聚合支付平台商户号',
  `device_no` varchar(16) NOT NULL DEFAULT '' COMMENT '设备号',
  `mer_order_no` varchar(32) NOT NULL COMMENT '商户订单号',
  `trade_type` tinyint(4) NOT NULL COMMENT '交易类型。1-主扫支付，2-被扫支付，3-关闭订单，4-订单退款，5-支付查询，6-退款查询',
  `total_fee` bigint(20) unsigned NOT NULL COMMENT '订单总金额',
  `cash_fee` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '现金支付金额',
  `coupon_fee` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '现金券金额。现金券支付金额<=订单总金额，订单总金额-现金券金额为现金支付金额',
  `fee_type` varchar(8) NOT NULL DEFAULT '' COMMENT '货币种类。人民币：CNY',
  `mer_tx_time` varchar(14) NOT NULL DEFAULT '' COMMENT '商户订单生成时间。yyyyMMddHHmmss',
  `mer_time_expire` varchar(14) NOT NULL DEFAULT '' COMMENT '商户订单超时时间。yyyyMMddHHmmss',
  `mer_order_desc` varchar(128) NOT NULL DEFAULT '' COMMENT '商户订单描述',
  `tx_status` tinyint(4) NOT NULL COMMENT '交易状态。1-未支付；2-成功；3-处理中；4-转入退款；5-未确定；6-已关闭；7-失败；8-转入代发，退款失败需线下退款。',
  `operation_date` varchar(8) NOT NULL DEFAULT '' COMMENT '商户运营日期。yyyyMMdd',
  `product_id` varchar(32) NOT NULL DEFAULT '' COMMENT '商户商品ID',
  `merchant_ip` varchar(16) NOT NULL DEFAULT '' COMMENT '商户订单生成的机器IP',
  `notify_url` varchar(256) NOT NULL DEFAULT '' COMMENT '商户回调通知地址',
  `req_reserved` varchar(128) NOT NULL DEFAULT '' COMMENT '附加信息，即请求保留域，会原样返回商户',
  `code_url` varchar(256) NOT NULL DEFAULT '' COMMENT '二维码链接',
  `code_img_url` varchar(256) NOT NULL DEFAULT '' COMMENT '二维码图片URL',
  `global_seq` varchar(32) NOT NULL DEFAULT '' COMMENT '全局跟踪号',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`tx_trade_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台交易表';

CREATE TABLE `tx_channel` (
  `tx_serial_no` varchar(32) NOT NULL COMMENT '交易流水号',
  `org_tx_serial_no` varchar(32) NOT NULL DEFAULT '' COMMENT '原交易流水号',
  `tx_trade_no` varchar(32) NOT NULL COMMENT '平台交易流水号',
  `tx_channel_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '渠道交易时间。请求发渠道的时间',
  `total_fee` bigint(20) unsigned NOT NULL COMMENT '订单总金额',
  `cash_fee` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '现金支付金额',
  `coupon_fee` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '现金券金额。现金券支付金额<=订单总金额，订单总金额-现金券金额为现金支付金额',
  `fee_rate` decimal(5,2) NOT NULL DEFAULT '1.00' COMMENT '费率',
  `fee_type` varchar(8) NOT NULL DEFAULT '' COMMENT '货币种类。人民币：CNY',
  `trade_type` tinyint(4) DEFAULT NULL COMMENT '交易类型。1-主扫支付，2-被扫支付，3-关闭订单，4-订单退款，5-支付查询，6-退款查询',
  `tx_status` tinyint(4) NOT NULL COMMENT '交易状态。1-未支付；2-成功；3-渠道处理中；4-转入退款；5-渠道未确定；6-已关闭；7-失败；8-转入代发，退款失败需线下退款；9-渠道前置未受理',
  `channel_id` tinyint(4) NOT NULL COMMENT '渠道ID。1-银联',
  `channel_mer_id` varchar(32) NOT NULL COMMENT '渠道商户号',
  `channel_group` varchar(16) NOT NULL COMMENT '前置分组',
  `out_serial_no` varchar(32) NOT NULL DEFAULT '' COMMENT '外部渠道流水号',
  `out_end_time` varchar(14) NOT NULL DEFAULT '' COMMENT '外部渠道交易结束时间。yyyyMMddHHmmss',
  `out_settle_date` varchar(8) NOT NULL DEFAULT '' COMMENT '外部渠道交易清算日期。yyyyMMdd',
  `out_resp_code` varchar(32) NOT NULL DEFAULT '' COMMENT '外部渠道返回码',
  `out_resp_desc` varchar(128) NOT NULL DEFAULT '' COMMENT '外部渠道返回描述',
  `code_url` varchar(256) NOT NULL DEFAULT '' COMMENT '二维码链接',
  `code_img_url` varchar(256) NOT NULL DEFAULT '' COMMENT '二维码图片URL',
  `out_trade_type` varchar(32) NOT NULL DEFAULT '' COMMENT '外部渠道交易类型',
  `out_third_party_no` varchar(32) NOT NULL DEFAULT '' COMMENT '外部渠道第三方订单号',
  `req_reserved` varchar(128) NOT NULL DEFAULT '' COMMENT '附加信息，即请求保留域，会原样返回商户',
  `global_seq` varchar(32) NOT NULL DEFAULT '' COMMENT '全局跟踪号',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`tx_serial_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='渠道交易表';

